# Generated by Django 5.2.8 on 2025-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="founditem",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lostclaim",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
