# Generated by Django 5.2.8 on 2025-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_founditem_contact_email_lostclaim_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="founditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="found_items/"),
        ),
        migrations.AddField(
            model_name="lostclaim",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lost_items/"),
        ),
    ]
