# Generated by Django 5.2.8 on 2025-11-28 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_founditem_image_lostclaim_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="founditem",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
